# Generated by Django 4.2.5 on 2023-10-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('agency', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('addre', models.CharField(max_length=100)),
            ],
        ),
    ]
