# Generated by Django 4.2.5 on 2023-10-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0002_alter_property_addre_alter_property_agency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('firm', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=250, null=True)),
                ('desic', models.CharField(blank=True, max_length=250, null=True)),
                ('addre', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
