# Generated by Django 4.2.5 on 2023-10-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0003_category_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='upload_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='property_img/'),
        ),
    ]
