# Generated by Django 4.2.5 on 2023-10-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0004_property_upload_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='upload_img',
            field=models.ImageField(upload_to=None),
        ),
    ]
