# Generated by Django 4.2.5 on 2023-10-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0005_alter_property_upload_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='uploadfile',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='property_img/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='upload_img',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='property_img/'),
        ),
    ]
