# Generated by Django 4.2.5 on 2023-10-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0007_category_registration_upload_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_registration',
            name='upload_img',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='category_registration',
            name='uploadfile',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
    ]
