# Generated by Django 4.2.5 on 2023-11-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0010_alter_category_registration_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_registration',
            name='uploadfile',
            field=models.FileField(default=None, max_length=280, null=True, upload_to='property_img/'),
        ),
    ]
