# Generated by Django 4.2.5 on 2023-11-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0011_alter_category_registration_uploadfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('cnic', models.IntegerField(blank=True, max_length=200, null=True)),
                ('phone', models.IntegerField(blank=True, max_length=250, null=True)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
